// Generated by CoffeeScript 1.8.0
(function() {
  var app, http, io;

  app = require('express')();

  http = require('http').Server(app);

  io = require('socket.io')(http);

  app.get('/', function(req, res) {
    return res.sendFile(__dirname + '/index.html');
  });

  io.on('connection', function(socket) {
    socket.emit('news', {
      title: 'Welcome to World News',
      contents: 'This news flash was sent from Node.js!',
      allowResponse: true
    });
    return socket.on('scoop', function(data) {
      return socket.emit('news', {
        title: 'Circular Emissions Worked',
        contents: 'Received this content: ' + data.contents
      });
    });
  });

  http.listen(8080, function() {
    return console.log('listening on *:8080');
  });

}).call(this);

//# sourceMappingURL=server.js.map
