// Generated by CoffeeScript 1.8.0
(function() {
  var app, fs, handler, html, io, tick;

  fs = require('fs');

  html = fs.readFileSync('index.html', 'utf8');

  handler = function(req, res) {
    res.setHeader('Content-Type', 'text/html');
    res.setHeader('Content-Length', Buffer.byteLength(html, 'utf8'));
    return res.end(html);
  };

  app = require('http').createServer(handler);

  tick = function() {
    var now;
    now = new Date().toUTCString();
    return io.sockets.send(now);
  };

  setInterval(tick, 1000);

  app.listen(3001);

  io = require('socket.io').listen(app);

}).call(this);

//# sourceMappingURL=server.js.map
