// Generated by CoffeeScript 1.8.0
(function() {
  var app, createWatcher, express, fs, http, io, path, root, server, url, watchers;

  fs = require('fs');

  url = require('url');

  http = require('http');

  path = require('path');

  express = require('express');

  app = express();

  server = http.createServer(app);

  io = require('socket.io').listen(server);

  root = __dirname;

  app.use(function(req, res, next) {
    req.on('static', function() {
      var file, mode;
      file = url.parse(req.url).pathname;
      mode = 'stylesheet';
      if (file[file.length - 1] === '/') {
        file += 'index.htm';
        mode = 'reload';
      }
      return createWatcher(file, mode);
    });
    return next();
  });

  app.use(express["static"](root));

  watchers = {};

  createWatcher = function(file, event) {
    var absolute;
    absolute = path.join(root, file);
    if (watchers[absolute]) {
      return;
    }
    fs.watchFile(absolute, function(curr, prev) {
      if (curr.mtime !== prev.mtime) {
        return io.sockets.emit(event, file);
      }
    });
    return watchers[absolute] = true;
  };

  app.listen(3001);

}).call(this);

//# sourceMappingURL=server.js.map
